---
version: "3.6"
services:
  kongdbless:
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    image: "kong/kong-gateway:2.8.0.0-alpine"
    networks:
      - kong-net
    ports:
      - "8000-8004:8000-8004"
      - "8443-8445:8443-8445"
    #restart: always
    shm_size: 256m
    volumes:
      - "/srv/kong:/kong/declarative/"

networks:
  kong-net:
    driver: bridge
